# Generated by Django 3.2 on 2023-03-23 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('employee_id', models.IntegerField()),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('joindate', models.DateField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('qrcode', models.ImageField(blank=True, upload_to='qrimage/')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('employee_id', models.IntegerField()),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=100)),
                ('stipend', models.CharField(default='', max_length=1000)),
                ('joindate', models.DateField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('qrcode', models.ImageField(blank=True, upload_to='qrimage/')),
            ],
            options={
                'ordering': ('employee_id',),
            },
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('employee_id', models.IntegerField()),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=100)),
                ('joindate', models.DateField(null=True)),
                ('resignationdate', models.DateField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('qrcode', models.ImageField(blank=True, upload_to='qrimage/')),
            ],
            options={
                'ordering': ('employee_id',),
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('employee_id', models.IntegerField()),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=1000)),
                ('joindate', models.DateField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('qrcode', models.ImageField(blank=True, upload_to='qrimage/')),
            ],
            options={
                'ordering': ('employee_id',),
            },
        ),
        migrations.CreateModel(
            name='Reexp',
            fields=[
                ('employee_id', models.IntegerField()),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=100)),
                ('joindate', models.DateField(null=True)),
                ('resignationdate', models.DateField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('qrcode', models.ImageField(blank=True, upload_to='qrimage/')),
            ],
            options={
                'ordering': ('employee_id',),
            },
        ),
        migrations.CreateModel(
            name='Rejected',
            fields=[
                ('employee_id', models.IntegerField()),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ('employee_id',),
            },
        ),
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('employee_id', models.IntegerField()),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=2000)),
                ('date', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('qrcode', models.ImageField(blank=True, upload_to='qrimage/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
            ],
        ),
    ]
