# Generated by Django 3.2 on 2023-03-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html2pdf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='stipend',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
