# Generated by Django 3.2 on 2022-12-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('html2pdf_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='qrcode',
        ),
        migrations.RemoveField(
            model_name='reexp',
            name='qrcode',
        ),
    ]
