# Generated by Django 3.2 on 2022-12-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html2pdf_app', '0002_auto_20221209_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to='qrimage/'),
        ),
        migrations.AddField(
            model_name='reexp',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to='qrimage/'),
        ),
    ]
