# Generated by Django 3.2 on 2022-12-23 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('html2pdf_app', '0004_auto_20221209_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('employee_id', models.IntegerField()),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('joindate', models.DateField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('qrcode', models.ImageField(blank=True, upload_to='qrimage/')),
            ],
        ),
    ]
